### ISSUE TITLE
sync-rsync.delete option

### ISSUE THREAD

**Issue by dghein** [thisboyiscrazy/vscode-rsync#37]
sorry for my confusion, but what does this option do? will it delete a file on remote if deleted locally? if not, is this a stupid feature to request? i tried setting this option and although sync on save seems to be functioning, deleting the file seems to have no affect. 

thanks for this plugin!

**Comment by thisboyiscrazy** [comment]
Yes by default rsync does not delete files, the "delete" flags tell rsync
to delete files to match the source to the destination.  There is no event
for "on delete" so can not fire off a sync when you delete a file.

Watchglob might detect file deletions. Otherwise you will have to manually
call a sync "Sync Local to Remote" or "Sync Remote to Local"

**Comment by dghein** [comment]
ok thanks for clearing that up. i don't mind working around this at all. thanks so much for developing this plugin - i was actually having a fair bit of trouble finding something good for vscode that could keep my remote dev server up to date as i worked. very much appreciated!!

**Comment by thisboyiscrazy** [comment]
That's exactly why I developed the plugin.
