### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by lazyc97** [thisboyiscrazy/vscode-rsync#48]
Instead of opening output every save, a short summary on notification would be nice. It will let us know which files are synced or some errors happened without having output pane open all the time.

![](https://code.visualstudio.com/assets/updates/1_21/notification-small.png)

**Comment by thisboyiscrazy** [comment]
I originally used notifications. But because there is no way for the extension to clear them they just got in the way. So I went with auto displaying/hiding the output window. With the recent revamp of how notifications are displayed, it might make sense to reexamine using them. Until then these settings might help:

* `sync-rsync.autoShowOutput`: Auto show rsync output when rsync is working.
* `sync-rsync.autoHideOutput`: Auto hide rsync output when rsync is done.

**Comment by lazyc97** [comment]
When I work with `onSave` or `onSaveIndiviual`, the transfer process is usually very fast. The output panel show up and close instantly and I can't tell if it fail or which files were transfered, hope there is an update soon 👍 .

**Comment by thisboyiscrazy** [comment]
If rsync has a non zero exit status it will show a notifcation. So if the sync failt it should show you.

**Comment by thisboyiscrazy** [comment]
@lazyc97 just pushed out a version with this. set 

```
"sync-rsync.notification": true
```
