### ISSUE TITLE
ability to enforce uni-directional sync per site

### ISSUE THREAD

**Issue by jimklo** [thisboyiscrazy/vscode-rsync#58]
So something I'd like to be able to do is only sync in one direction (local -> remote) for one site, but then for a different site I'd like to be able to sync in both directions (local -> remote and remote -> local).

Currently it seems this is global, so if I try to copy remote -> local, it does this for all sites (which I don't want, because this would cause the remote to sync many TB back that I don't want locally), but for certain specific folders or sites, I'd like to do this.

**Comment by thisboyiscrazy** [comment]
I just want to make sure I understand what you are looking for:

- Specify a site when doing a sync
- The ability to limit the direction of sync for a site

**Comment by artiswilliams** [comment]
I agree. It wasn't obvious to me that it was syncing all sites.

Here is the workflow I use and how it might work:
- I have ONE Workspace that is configured with all of the defaults and settings I like for my sites.  
- Then I add a folder to the workspace for the specific site that I'm working on at the moment.
- I setup the "sync-rsync.sites" for each site but I like to leave those settings in my Workspace Settings configuration so that I don't have to keep re-configuring them each time I add that Site (Folder)
- When I'm done working on a site I remove the folder from the Workspace but leave the "sync-rsync.sites" settings in the Workspace so that next time I add the folder back it just works.
-  **It would be nice if sync-rsync ignored any 'sites' that didn't have a corresponding "folders.path" in the Workspace Settings.  This way even "Sync All" would only sync folders that are added to the Workspace.**

Additionally, it might be nice to have a context menu (right-click) on a folder in the tree structure to "Sync this Folder - Local to Remote" "Sync this folder - Remote to Local"....assuming VSCode makes the context menu available for developers.

**Comment by jcontreras78** [comment]
Yes, I keep having the same problem... not only it can cause errors but it takes up more time and resources when all the sites in my dev server have to re-sync every time I want to get the latest code. and re-sync back up. I think it makes sense to only sync the current site I'm working on both ways.

I am with @artiswilliams on the proposed solution if possible. That will facilitate things when working on multiple sites. 

Thank you for that amazing plugin!

**Comment by jimklo** [comment]
agreed that syncing all sites in a workspace is somewhat a waste of resources, however it is mostly a  background task.. Only a problem if you have a dozen sites and you're just toggling back and forth between local and remote.

however the big thing for me is the one-way sync... I want to push code only... I don't want all the data that's on the server (that's in directories I can't really move easily).

Similarly it would be nice if it responded to any file change event... e.g. I add a new file outside of VS Code - it handles the sync when the editor see the filesystem change. But I'll leave that for a different feature request.

**Comment by thisboyiscrazy** [comment]
I will work on the context menu in another issue. For now I added command with (Single) after them for syncing a single site, I also added upOnly and downOnly to the site configs.

@jimklo Yes please make that another request. You may be able to do it with the watchGlob option.

**Comment by beeradmoore** [comment]
I had created a new issue with #75 which I have since closed as this appears to fix it. The (Single) command, I assumed it meant to would run sync one single time and then stop, not sync a single site.
