### ISSUE TITLE
Question : use includes/excludes on sync

### ISSUE THREAD

**Issue by momiji** [thisboyiscrazy/vscode-rsync#63]
Hello, have you ever tried to match includes/excludes to filename on single file save (and load) before calling rsync ?
The idea being to prevent calling rsync when not needed.
This will definitely be an important enhancement, just wanted to know if it is feasable before trying to do it :)

**Comment by thisboyiscrazy** [comment]
I have not because then I would have to implement rsync's pattern matching in the extension. I would welcome a pull request with the matching added. I agree it would be nice. But I saw it as infeasible, you would have to look the --include, --include-from, --exclude, --exclude-from , --filter, and a few others. Then implement rsync pattern matching in typescript. I saw it as just not worth it. But again I would welcome a pull request.
