### ISSUE TITLE
maybe you can use watcher to implement onSave?

### ISSUE THREAD

**Issue by zjjott** [thisboyiscrazy/vscode-rsync#8]
in vscode document:https://code.visualstudio.com/docs/extensions/example-language-server
```tscript
import { workspace, Disposable, ExtensionContext } from 'vscode';

workspace.createFileSystemWatcher('**/.clientrc')
```

**Comment by thisboyiscrazy** [comment]
I could but the introduces issues with detecting if the file is ignored by rsync's ignore.

**Comment by zjjott** [comment]
how about parse rsync's ignore and reload watcher?
`context.subscriptions` have `pop` and `push` function,is it useful?

**Comment by thisboyiscrazy** [comment]
The issue is it seems i would have to reimplement rsyncs ignore pattern
matching, unless you can think of another way?

**Comment by jacobweber** [comment]
I'm not exactly sure how createFileSystemWatcher works, but I did something similar to this in an Eclipse plugin. If you're syncing localDir to remoteDir, and it notifies you that a file localDir/foo/bar changed, you just need to sync the relative path to the file, using -R:

cd localDir && rsync -rltzv --delete -R foo/bar remoteDir/

Then you can still use the same include/exclude patterns, since they're relative to the root.

This would be very useful, if it allowed you to watch the whole directory and sync when there are any changes, instead of just syncing when you save a file.

**Comment by thisboyiscrazy** [comment]
That is actually implemented onSave, onSaveIndividual, watchGlobs depending on how you wanted it to work.
